In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('house_data.csv')
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [4]:
df['area_type'].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [5]:
df['availability'].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [6]:
df=df.drop(['area_type','society','balcony','availability'],axis=1)

In [7]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [8]:
df['location'].unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1306,), dtype=object)

In [9]:
df['location']=df['location'].fillna('Sarjapur Road')

In [10]:
df.isnull().sum()

location       0
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [11]:
df['size'].value_counts()
df['size']=df['size'].fillna('2 BHK')

In [12]:
medbath=df['bath'].median()
medbath
df['bath']=df['bath'].fillna(medbath)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12438 entries, 0 to 13318
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    12438 non-null  object
 1   size        12438 non-null  object
 2   total_sqft  12438 non-null  object
 3   bath        12438 non-null  float64
 4   price       12438 non-null  float64
dtypes: float64(2), object(3)
memory usage: 583.0+ KB

In [15]:
loc=df['location'].value_counts()
loc_less_than_10=loc[loc<=10]
df['location']=df['location'].apply(lambda x: 'others' if x in loc_less_than_10 else x)
df['location'].value_counts()

location
others                  2942
Whitefield               507
Sarjapur  Road           364
Electronic City          273
Thanisandra              224
                        ...
Tindlu                    11
Banashankari Stage V      11
Doddakallasandra          11
Thyagaraja Nagar          11
HAL 2nd Stage             11
Name: count, Length: 232, dtype: int64

In [16]:
out= [int(i.split()[0]) for i in df['size']]
df['bhk']=out
df.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [17]:
def clean_sqft(sqft):
    l= sqft.split('-')
    if len(l)==2:
        return (float(l[0])+float(l[1]))/2
    try:
        return float(l[0])
    except:
        return None
df['total_sqft']=df['total_sqft'].apply(clean_sqft)
df['total_sqft']=df['total_sqft'].fillna(round(df['total_sqft'].mean()))
df['total_sqft'].isna().sum()

np.int64(0)

In [18]:
df['price_per_sqft']=df['price']*100000/df['total_sqft']
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [19]:
df=df[df['total_sqft']/df['bhk']>=300]
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [20]:
df=df[df['bhk']<=6]
df=df[df['bath']< df['bhk']+2]

In [21]:
q1 =df['price_per_sqft'].quantile(0.25)
q3 =df['price_per_sqft'].quantile(0.75)

IQR=q3-q1

lower=q1-0.5*IQR
upper=q3+0.5*IQR
df=df[(df['price_per_sqft']>=lower) & (df['price_per_sqft']<=upper)]

In [22]:
df.reset_index(inplace=True)
df=df.drop(['index', 'size','price_per_sqft'],axis=1)

In [23]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [24]:
encoder=LabelEncoder()
df['encoded_location']=encoder.fit_transform(df['location'])
df.head()

                   location  total_sqft  bath   price  bhk  encoded_location
0  Electronic City Phase II      1056.0   2.0   39.07    2                75
1          Chikka Tirupathi      2600.0   5.0  120.00    4                58
2               Uttarahalli      1440.0   2.0   62.00    3               216
3        Lingadheeranahalli      1521.0   3.0   95.00    3               154
4                  Kothanur      1200.0   2.0   51.00    2               146

In [25]:
x=df.drop(['location','price'],axis=1)
y=df['price']

In [26]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3, random_state=42)

In [27]:
model=RandomForestRegressor(random_state=42)
params={
    'n_estimators':[100,150,200,250,300],
    'max_depth':[3,4,5,6,7]
}
grid=GridSearchCV(estimator=model,param_grid=params,cv=5)
grid.fit(xtrain,ytrain)
print('best parameters:',grid.best_params_)
print('best score:',grid.best_score_)

best parameters: {'max_depth': 7, 'n_estimators': 200}
best score: 0.8392662896023723

In [28]:
ypred=grid.predict(xtest)
ypred

array([82.69830238, 60.47217668, 69.50411056, ..., 72.26302008,
       60.72630468, 63.60012034], shape=(2809,))

In [29]:
print('train score:',grid.score(xtrain,ytrain))
print('test score:',grid.score(xtest,ytest))

train score: 0.907107235019709
test score: 0.8106843944930373

In [30]:
df.to_csv('cleaned_df.csv')

In [31]:
import joblib
with open('rf_model.joblib','wb') as file:
    joblib.dump(grid,file)